node {
    
    
    stage('Checking out MyThaiStar') {
        deleteDir()
        git branch: 'develop', credentialsId: 'githubacc', url: 'https://github.com/Smithes/MTS/'
    }

    stage('Loading Custom Tools') {
     // tool 'Node 8.4'
        def node = tool name: 'Node 8.9 LTS', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        env.PATH = "${node}/bin:${env.PATH}"
        // tool 'Angular CLI'
        
        tool 'Chrome-stable'
        // tool 'Yarn'
    }
    
    stage('Fresh Dependency Installation') {
        sh """
            cd angular
            #find . -name "node_modules" -exec rm -rf '{}' +
            npm install
            #yarn
        """
    }
    
    stage('Code Linting') {
        sh """
            cd angular
            npm run lint
        """
    }
    
    stage('Execute Angular tests') {
        sh """
            cd angular
            ng test --browsers ChromeHeadless --single-run
        """
        // ansiColor('xterm'){
        // }
    }
    
    stage('Build Application') {
        sh """
            cd angular
            ng build --aot --environment=prod
        """
    }
    
    stage('Deployment') {
        //sshagent (credentials: ['deploykey']) {
        sshagent (credentials: ['deployphrase']) {    
            sh """
                cd angular
                # Copy resulting "dist" folder from workspace to deployment server
                scp -o StrictHostKeyChecking=no -r dist root@10.40.235.122:/root/smithes/mythaistar/angular/
                
                # Launch application in Docker container
                ssh -o StrictHostKeyChecking=no root@10.40.235.122 docker rm -f smts-angular
                ssh -o StrictHostKeyChecking=no root@10.40.235.122 docker run -itd --name=smts-angular -p 8091:80 nginx
                ssh -o StrictHostKeyChecking=no root@10.40.235.122 docker exec smts-angular bash -c \\"rm /usr/share/nginx/html/*\\"
                ssh -o StrictHostKeyChecking=no root@10.40.235.122 docker cp smithes/mythaistar/angular/dist/. smts-angular:/usr/share/nginx/html/
            """
        }
        sh 'echo \\"Application available at http://de-muc-mythai:8091\\"'
    } 
}
